name: 'oci-token-exchange-action'
description: 'Exchange GitHub OIDC ID Token for OCI Session token for use in the GitHub Actions workflow job'
branding:
  color: red
  icon: cloud
inputs:
  client_id:  
    description: 'client_id of OCI Domain Confidential Application'
    required: true
  client_secret:  
    description: 'client_secret of OCI Domain Confidential Application'
    required: true
  domain_base_url:  
    description: 'Base URL of OCI Domain that provides the token exchange endpoint'
    required: true
  oci_tenancy:  
    description: 'OCI Tenancy'
    required: true
  oci_region:  
    description: 'OCI Region'
    required: true
  test_token:
    description: 'Test token to exchange'
    required: false
runs:
  using: 'node20'
  main: 'dist/main.js'
