name: Run OCI Token Exchange Action
 
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'
 
    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash
  
    - name: Run OCI Token Exchange Action
      uses: claytonrb/oci-token-exchange-action@multi-platform
      with:
        domain_base_url: 'https://idcs-3483e738246c43fbb9649b351956fa9f.identity.oraclecloud.com'
        oci_tenancy: 'ocid1.tenancy.oc1..aaaaaaaavpzodvldgdq243osqyixczvdnity4gg2l4yq7rj5n4pda2ifhqxq'
        oci_region: 'sa-vinhedo-1'
        # test_token: ${{ secrets.
        oidc_client_identifier: '1171da4b967a426bb92d3b94a6dbd13e:idcscs-b2c3aa88-cbd4-4f8a-b55c-77f7a44ad66f'
        retry_count: '3' 
        ci_platform: 'github'   
 
    - name: Run OCI CLI Command
      run: oci   --auth security_token os bucket get --bucket-name actionDemo4   --namespace-name axyuj7175o0j ; oci  --auth security_token os bucket list --compartment-id ocid1.compartment.oc1..aaaaaaaaqpkqyaouunf3xwm75ix7vfv76vc2ffey4bd6zotqsbbdxfsrypaq   --namespace-name axyuj7175o0j ; oci  --auth security_token os object put --bucket-name actionDemo4 --name ./LICENSE.txt --file LICENSE.txt  --content-type text/plain

