name: Run OCI Token Exchange Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '22.8.0'

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
      shell: bash

    - name: Install dependencies
      run: npm install

    - name: Run OCI Token Exchange Action
      uses: gtrevorrow/oci-token-exchange-action@main
      with:
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        domain_base_url: ${{ vars.DOMAIN_BASE_URL }}
        oci_user: ${{ secrets.OCI_USER }}
        oci_tenancy: ${{ vars.OCI_TENANCY }}
        oci_region: ${{ vars.OCI_REGION }}
        # test_token: ${{ secrets.ACCESS_TOKEN_TEST }}

    - name: Debug Print
      run: |
        echo "OCI Private Key file:"
        cat $HOME/private_key.pem
        echo "OCI Public Key file:"
        cat $HOME/public_key.pem
        echo "OCI UPST Session"
        cat $HOME/session

    - name: List OCI Config
      run: cat ~/.oci/config

    - name: Run OCI CLI Command
      run: |
        /home/runner/bin/oci --auth security_token iam region list --all
    
