name: Run OCI Token Exchange Action
 
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20'

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash

    - name: Run OCI Token Exchange Action
      uses: gtrevorrow/oci-token-exchange-action@multi-platform
      with:
        domain_base_url: 'https://idcs-3483e738246c43fbb9649b351956fa9f.identity.oraclecloud.com'
        oci_tenancy: 'ocid1.tenancy.oc1..aaaaaaaavpzodvldgdq243osqyixczvdnity4gg2l4yq7rj5n4pda2ifhqxq'
        oci_region: 'sa-vinhedo-1'
        # test_token: ${{ secrets.
        oidc_client_identifier: '7080c6072e2e4f979ce58cf9211a350d:idcscs-b7f80843-11b7-4aa9-b52d-43a74d075edd'
        retry_count: '3' 
        ci_platform: 'github' 

    - name: Run OCI CLI Command
      run: oci --auth security_token os bucket create --compartment-id     --name actionDemo1 --namespace-name axyuj7175o0j

